Indian_oil_ethanol <- read_excel("D:/Dhruva/Indian_oil_ethanol.xlsx")
attach(Indian_oil_ethanol)
hist(`Mileage with ethanol`)
library(moments)
skewness(`Mileage with ethanol`)
kurtosis(`Mileage with ethanol`)
shapiro.test(`Mileage with ethanol`)
library(nortest)
lillie.test(`Mileage with ethanol`)
ad.test(`Mileage with ethanol`)
