data = iris
attach(iris)
library(ggplot2)
ggplot(data,aes(1:150,Sepal.Length))+geom_line()
ggplot(data,aes(Sepal.Length,Sepal.Width))+geom_point()
ggplot(data,aes(Species,Sepal.Length))+geom_col()
ggplot(data,aes(Sepal.Length))+geom_bar()
ggplot(data,aes(Sepal.Length))+geom_histogram(bins=15)
ggplot(data,aes(Sepal.Length))+geom_density()
ggplot(data,aes(Sepal.Length))+geom_boxplot()
ggplot(data,aes(Species,Sepal.Length))+geom_violin()
ggplot(data,aes(Sepal.Length,Sepal.Width,colour=Species)+geom_point()+labs(title = "Scatter plot",subtitle = "Sepal",x="x label",y="y label",caption = "graph using ggplot")
IrisPlot <- ggplot(iris, aes(Sepal.Length, Petal.Length, colour=Species)) + geom_point()
print(IrisPlot)
ggplot(data,aes(Sepal.Length,Sepal.Width,colour=Species))+geom_point()
ggplot(data,aes(Sepal.Length,Sepal.Width))+geom_point()
ggplot(data,aes(Sepal.Length,Sepal.Width,colour=Species))+geom_point()
print(IrisPlot+labs(x='x label',y='y label')+ggtitle("graph using ggplot"))
ggplot(data,aes(Sepal.Length,Sepal.Width))+geom_point()+theme(legend.position = "none")
ggplot(data,aes(Sepal.Length,Sepal.Width))+geom_point()+theme(legend.title = element_blank())
+theme(legend.position = "top")
+theme(legend.position = "bottom")
mean()
median()
mode()
sd()
library(moments)
kurtosis(Sepal.Length)
skewness(Sepal.Length)
kurt()
skewness()

str(df)
nrow(df)
ncol()
length()
colnames()
names()

colnames(df)=c('c1','c2')

df=read.csv("76_attributes_heartdiseases.csv")
df=read.csv("data/76_attributes_heartdiseases.csv")
summary(df)
mean(df$V5)
median(df$V10)
mode(df$V5)
library(moments)
skewness(df$V5)
kurtosis(df$V5)

skewness(df$V3)
kurtosis(df$V3)

df_1=subset(df,df$V1>20)
write.csv(df,df_2.csv)
write.csv(m2_df,"new_df.csv")
write.csv(df,"76_attributes_heartdiseases.csv")
